### ISSUE TITLE
Console example not working

### ISSUE THREAD

**Issue by Snowfire01** [ioncodes/JodelAPI#3] opened 2016-11-15 21:22 UTC
I referenced the JodelAPI.dll in my project and and tried the code form the Console project's main method. I also downloaded the solution and tried it directly in there, but it didn't change anything.

Everytime I try to run the console example (or similar code with different latitude, longitude, etc.) the server returns an error: (477) unknown

**Comment by rasmusenhorning** [comment] 2016-11-15 21:29
This started in the beginning of november after Jodel released an update. The problem is the method for retrieving an access token, which stopped working after the update. A work-around is retrieving an access token from the real application on a device with the help of mitmproxy or something similar. If you have an access token, the rest of the API works fine.

**Comment by ioncodes** [comment] 2016-11-16 08:03
@Snowfire01 This is correct, however, the console does not work at this point, because i did not upgrade it to work with the current version of the JodelAPI. The main change is the conversion from static context to nonstatic.
I'm working on the README and then I'll upgrade the console.

However, @rasmusenhorning  is right. At the current point you need to use your own access token which you can obtain via mitmproxy or if you're on iOS you can look it up in the app.

I will update API as soon as possible, I already have a working version but it's unstable.

**Comment by tobilap** [comment] 2016-11-21 17:17
Any news on the Token generation?

**Comment by ioncodes** [comment] 2016-11-21 17:25
@tobilap no, but I will look into it soon.

**Comment by ioncodes** [comment] 2016-11-22 16:13
Make sure you *clone* the repo and build it. The appveyor link is outdated. Will fix it in a few hours.
However, the problems should be fixed now.

**Closed by ioncodes** 2016-11-22 16:13 UTC
